In [3]:
import numpy as np

In [4]:
np.median([12,31,15,26])                # calculates median of the data

20.5

In [5]:
np.mean([12,31,15,26])                  # calculates mean of the given data

21.0

In [6]:
np.median([12,31,15,26,120])            # median of data including outlier

26.0

In [7]:
np.mean([12,31,15,26,120])              # mean of data including outlier

40.8

In [8]:
np.random.randint([12,31,15,26,120])

array([ 6, 18,  7, 10, 13])

In [9]:
np.random.randint(10,50,5)

array([13, 17, 22, 17, 10])

In [12]:
l = [1, 2, 3, 4]

In [13]:
r1 = np.array(l)                       # create array of list l

In [14]:
r1

array([1, 2, 3, 4])

In [15]:
r1.ndim                                # no. of dimensions of array

1

In [16]:
l2 = [[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]]     # 2 brackets for 2 dimensional array

In [17]:
r2 = np.array(l2)

In [18]:
r2

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [19]:
r2.ndim

2

In [20]:
l3 = [[[10, 20, 30], [100, 200, 300], [1000, 2000, 3000]]]

In [21]:
np.array(l3)

array([[[  10,   20,   30],
        [ 100,  200,  300],
        [1000, 2000, 3000]]])